name: Build APK Fixed

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          build-essential \
          python3-pip \
          python3-setuptools
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        
    - name: Build with Buildozer
      run: |
        buildozer init
        # استفاده از requirements ساده‌تر
        echo "[app]
title = LicenseManager
package.name = licensemanager
package.domain = ir.mpt
source.dir = .
version = 0.1
requirements = python3,kivy==2.1.0
orientation = portrait

[buildozer]
log_level = 2

[android]
api = 33
minapi = 21
ndk = 25b
android.permissions = INTERNET

[android:entrypoint]
main = main.py" > buildozer.spec
        
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: licensemanager-apk
        path: bin/*.apk
        retention-days: 7
